# Generated by Django 2.1.2 on 2018-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombrecompleto', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('password', models.CharField(max_length=50)),
                ('ciudad', models.ManyToManyField(to='movies.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre mascota')),
                ('descripcion', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='albums/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Razaprodominante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mascotas',
            name='razap',
            field=models.ManyToManyField(to='movies.Razaprodominante'),
        ),
        migrations.AddField(
            model_name='interesados',
            name='region',
            field=models.ManyToManyField(to='movies.Region'),
        ),
        migrations.AddField(
            model_name='interesados',
            name='vivienda',
            field=models.ManyToManyField(to='movies.Vivienda'),
        ),
    ]
