# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181031_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
