# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20181105_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
