# Generated by Django 2.1.3 on 2018-11-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_director_studio_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
